### ISSUE TITLE
Alternative Implementation

### ISSUE THREAD

**Issue by splitbrain** [Visiopaja/dokuwiki-plugin-oauthazure#1]
Hi @Visiopaja, what a coincidence - I'm currently working on a oauthazure plugin myself. It does go a bit further than simply copying the keycloak plugin. It also interacts with the Microsoft graph API to fetch group memberships and is a bit more tailored towards the Azure specifics. Would you mind if I replace your implementation with mine when I'm ready to release?

**Comment by Visiopaja** [comment]
Hi,

It's nice to hear that there is a tailored plugin coming for the Azure oauth functionality. Feel free to replace my plugin after you are finished with the new one.

-Matias
________________________________
Lähettäjä: Andreas Gohr ***@***.***>
Lähetetty: keskiviikko 5. lokakuuta 2022 11.31
Vastaanottaja: Visiopaja/dokuwiki-plugin-oauthazure ***@***.***>
Kopio: Git ***@***.***>; Mention ***@***.***>
Aihe: [Visiopaja/dokuwiki-plugin-oauthazure] Alternative Implementation (Issue #1)


Hi @Visiopaja<https://github.com/Visiopaja>, what a coincidence - I'm currently working on a oauthazure plugin myself. It does go a bit further than simply copying the keycloak plugin. It also interacts with the Microsoft graph API to fetch group memberships and is a bit more tailored towards the Azure specifics. Would you mind if I replace your implementation with mine when I'm ready to release?

**Comment by splitbrain** [comment]
The new plugin has been released. Thank you.
